//! Email-code authentication handlers.
//!
//! Implements Ledger's 3-step passwordless email verification flow:
//! 1. `POST /v1/auth/email/initiate` — send verification code
//! 2. `POST /v1/auth/email/verify` — verify code, get session or onboarding token
//! 3. `POST /v1/auth/email/complete` — complete registration for new users

use std::time::Instant;

use axum::{Json, extract::State};
use axum_extra::extract::cookie::CookieJar;
use inferadb_control_core::SdkResultExt;
use inferadb_ledger_sdk::EmailVerificationResult;
use inferadb_ledger_types::Region;
use serde::{Deserialize, Serialize};

use super::{
    auth::set_token_cookies,
    common::{require_ledger, validate_email, validate_name},
    state::ApiError,
};
use crate::handlers::AppState;

// ── Request Types ───────────────────────────────────────────────────────

/// Request body for initiating email verification.
#[derive(Debug, Deserialize)]
pub struct InitiateRequest {
    pub email: String,
    /// Data residency region for the user's PII.
    /// Defaults to US_EAST_VA if not specified.
    pub region: Option<Region>,
}

/// Request body for verifying an email code.
#[derive(Debug, Deserialize)]
pub struct VerifyRequest {
    pub email: String,
    pub code: String,
    /// Data residency region for the user's PII.
    /// Defaults to US_EAST_VA if not specified.
    pub region: Option<Region>,
}

/// Request body for completing new-user registration.
#[derive(Debug, Deserialize)]
pub struct CompleteRegistrationRequest {
    pub onboarding_token: String,
    pub email: String,
    pub name: String,
    pub organization_name: String,
    /// Data residency region for the user's PII.
    /// Defaults to US_EAST_VA if not specified.
    pub region: Option<Region>,
}

// ── Response Types ──────────────────────────────────────────────────────

/// Response confirming that a verification code was sent.
#[derive(Debug, Serialize)]
pub struct InitiateResponse {
    pub message: &'static str,
}

/// Response from email code verification, varying by user state.
#[derive(Debug, Serialize)]
#[serde(tag = "status")]
pub enum VerifyResponse {
    /// Existing user without TOTP — session created.
    #[serde(rename = "authenticated")]
    Authenticated { access_token: String, refresh_token: String, token_type: &'static str },
    /// Existing user with TOTP — second factor required.
    #[serde(rename = "totp_required")]
    TotpRequired {
        /// Base64-encoded challenge nonce for TOTP verification.
        challenge_nonce: String,
    },
    /// New user — must complete registration.
    #[serde(rename = "registration_required")]
    RegistrationRequired { onboarding_token: String },
}

/// Registration data returned after completing onboarding.
#[derive(Debug, Serialize)]
pub struct CompleteRegistrationData {
    pub user: u64,
    pub organization: Option<u64>,
    pub access_token: String,
    pub refresh_token: String,
    pub token_type: &'static str,
}

/// Envelope response wrapping [`CompleteRegistrationData`].
#[derive(Debug, Serialize)]
pub struct CompleteRegistrationResponse {
    pub registration: CompleteRegistrationData,
}

// ── Helpers ─────────────────────────────────────────────────────────────

/// Returns the default region when none is specified.
fn default_region() -> Region {
    Region::US_EAST_VA
}

// ── Handlers ────────────────────────────────────────────────────────────

/// POST /control/v1/auth/email/initiate
///
/// Sends a 6-character verification code to the provided email address.
/// The code is generated by Ledger and sent via Control's SMTP service.
pub async fn initiate(
    State(state): State<AppState>,
    Json(body): Json<InitiateRequest>,
) -> Result<Json<InitiateResponse>, ApiError> {
    validate_email(&body.email)?;
    let ledger = require_ledger(&state)?;

    let region = body.region.unwrap_or_else(default_region);

    let start = Instant::now();
    let result = ledger
        .initiate_email_verification(&body.email, region)
        .await
        .map_sdk_err_instrumented("initiate_email_verification", start)?;

    // Send the code via email (fire-and-forget)
    if let Some(ref email_service) = state.email_service {
        let email = body.email.clone();
        let code = result.code.clone();
        let svc = email_service.clone();
        tokio::spawn(async move {
            let subject = "Your InferaDB verification code";
            let body_html = format!(
                "<p>Your verification code is: <strong>{code}</strong></p>\
                 <p>This code expires in 10 minutes.</p>"
            );
            let body_text =
                format!("Your verification code is: {code}\n\nThis code expires in 10 minutes.");
            if let Err(e) = svc.send_email(&email, subject, &body_html, &body_text).await {
                tracing::warn!(error = %e, "Failed to send verification email");
            }
        });
    } else {
        tracing::warn!(
            "Email service not configured — verification code generated but cannot be delivered"
        );
    }

    Ok(Json(InitiateResponse { message: "verification code sent" }))
}

/// POST /control/v1/auth/email/verify
///
/// Verifies the code and returns one of:
/// - Session tokens (existing user, no TOTP)
/// - TOTP challenge nonce (existing user with TOTP)
/// - Onboarding token (new user)
pub async fn verify(
    State(state): State<AppState>,
    jar: CookieJar,
    Json(body): Json<VerifyRequest>,
) -> Result<(CookieJar, Json<VerifyResponse>), ApiError> {
    let ledger = require_ledger(&state)?;

    let region = body.region.unwrap_or_else(default_region);

    let start = Instant::now();
    let result = ledger
        .verify_email_code(&body.email, &body.code, region)
        .await
        .map_sdk_err_instrumented("verify_email_code", start)?;

    match result {
        EmailVerificationResult::ExistingUser { session, .. } => {
            let jar = set_token_cookies(jar, &session);
            Ok((
                jar,
                Json(VerifyResponse::Authenticated {
                    access_token: session.access_token,
                    refresh_token: session.refresh_token,
                    token_type: "Bearer",
                }),
            ))
        },
        EmailVerificationResult::TotpRequired { challenge_nonce } => {
            use base64::Engine;
            let nonce_b64 = base64::engine::general_purpose::STANDARD.encode(&challenge_nonce);
            Ok((jar, Json(VerifyResponse::TotpRequired { challenge_nonce: nonce_b64 })))
        },
        EmailVerificationResult::NewUser { onboarding_token } => {
            Ok((jar, Json(VerifyResponse::RegistrationRequired { onboarding_token })))
        },
    }
}

/// POST /control/v1/auth/email/complete
///
/// Completes registration for a new user. Creates user + default organization.
/// Returns session tokens.
pub async fn complete(
    State(state): State<AppState>,
    jar: CookieJar,
    Json(body): Json<CompleteRegistrationRequest>,
) -> Result<(CookieJar, Json<CompleteRegistrationResponse>), ApiError> {
    validate_email(&body.email)?;
    validate_name(&body.name)?;
    validate_name(&body.organization_name)?;
    let ledger = require_ledger(&state)?;

    let region = body.region.unwrap_or_else(default_region);

    let start = Instant::now();
    let result = ledger
        .complete_registration(
            &body.onboarding_token,
            &body.email,
            region,
            &body.name,
            &body.organization_name,
        )
        .await
        .map_sdk_err_instrumented("complete_registration", start)?;

    let jar = set_token_cookies(jar, &result.session);

    Ok((
        jar,
        Json(CompleteRegistrationResponse {
            registration: CompleteRegistrationData {
                user: result.user.value(),
                organization: result.organization.map(|o| o.value()),
                access_token: result.session.access_token,
                refresh_token: result.session.refresh_token,
                token_type: "Bearer",
            },
        }),
    ))
}
